global using _8F;
global using _8F.Models;
global using _8F.Services;
global using _8F.Services.Interfaces;
global using _8F.Services.Implementations;
global using _8F.ViewModels;
global using _8F.Views;
global using _8F.Commands;
global using _8F.Helpers;
